/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "RNPrismRnSpecJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativePrismRnCxxSpecJSI_multiply(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativePrismRnCxxSpecJSI *>(&turboModule)->multiply(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber(),
    count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asNumber()
  );
}
static jsi::Value __hostFunction_NativePrismRnCxxSpecJSI_multiply2(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativePrismRnCxxSpecJSI *>(&turboModule)->multiply2(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber(),
    count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asNumber()
  );
}

NativePrismRnCxxSpecJSI::NativePrismRnCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("Prism-Rn", jsInvoker) {
  methodMap_["multiply"] = MethodMetadata {2, __hostFunction_NativePrismRnCxxSpecJSI_multiply};
  methodMap_["multiply2"] = MethodMetadata {2, __hostFunction_NativePrismRnCxxSpecJSI_multiply2};
}


} // namespace facebook::react
